# Generated by Django 3.2.8 on 2021-12-17 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_app', '0064_feedback_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='registered_user',
            name='Negative_balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='events',
            name='image',
            field=models.ImageField(default='', upload_to='=club_app/images'),
        ),
    ]
